import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    {
      // Dev-only: serve a fake __port__.js so the frontend talks to the
      // local FastAPI backend at 127.0.0.1:8000. In production this file is
      // generated by main.py with the actual random port.
      name: 'cf-dev-port',
      configureServer(server) {
        server.middlewares.use('/__port__.js', (_req, res) => {
          res.setHeader('Content-Type', 'application/javascript')
          res.setHeader('Cache-Control', 'no-store, max-age=0')
          res.end('window.__CF_PORT__ = 8000;')
        })
      },
    },
  ],
  base: './',
  build: {
    outDir: '../assets',
  },
  server: {
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      },
    },
  },
})
